version: '3.8' # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  ubuntu-c:
    hostname: ubuntu-c
    container_name: ubuntu-c
    image: bruchbude.nsupdate.info:9002/init-lab/lab_ubuntu-c:latest
    ports: 
     - ${UBUNTUC_PORT_SSHD}:22
     - ${UBUNTUC_PORT_TTYD}:7681
    privileged: true
    tty: true
    cap_add:
      - CAP_SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu-c/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu-c/root:/root
    networks:
     - diveinto.io

  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image: bruchbude.nsupdate.info:9002/init-lab/lab_ubuntu:latest
    ports: 
     - ${UBUNTU1_PORT_SSHD}:22
     - ${UBUNTU1_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu1/root:/root
    networks:
     - diveinto.io

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    image: bruchbude.nsupdate.info:9002/init-lab/lab_ubuntu:latest
    ports: 
     - ${UBUNTU2_PORT_SSHD}:22
     - ${UBUNTU2_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu2/root:/root
    networks:
     - diveinto.io

  ubuntu3:
    hostname: ubuntu3
    container_name: ubuntu3
    image: bruchbude.nsupdate.info:9002/init-lab/lab_ubuntu:latest
    ports: 
     - ${UBUNTU3_PORT_SSHD}:22
     - ${UBUNTU3_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu3/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu3/root:/root
    networks:
     - diveinto.io

  centos1:
    hostname: centos1
    container_name: centos1
    image: bruchbude.nsupdate.info:9002/init-lab/lab_centos:latest
    ports: 
     - ${CENTOS1_PORT_SSHD}:22
     - ${CENTOS1_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
     - diveinto.io

  centos2:
    hostname: centos2
    container_name: centos2
    image: bruchbude.nsupdate.info:9002/init-lab/lab_centos:latest
    ports: 
     - ${CENTOS2_PORT_SSHD}:22
     - ${CENTOS2_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos2/root:/root
    networks:
     - diveinto.io

  centos3:
    hostname: centos3
    container_name: centos3
    image: bruchbude.nsupdate.info:9002/init-lab/lab_ubuntu-c:latest
    ports: 
     - ${CENTOS3_PORT_SSHD}:22
     - ${CENTOS3_PORT_TTYD}:7681
    privileged: true
    tty: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos3/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos3/root:/root
    networks:
     - diveinto.io

  # Docker in Docker
  #
  # Usage: on host that wishes to use docker
  #
  # sudo apt-get update
  # sudo apt -y install docker.io
  # export DOCKER_HOST=tcp://docker:2375
  # docker ps -a
  #
  docker:
    hostname: docker
    container_name: docker
    image: bruchbude.nsupdate.info:9002/init-lab/lab_dind:latest
    privileged: true
    volumes:
     - ${ANSIBLE_HOME}/shared:/shared
    networks:
     - diveinto.io

  portal:
    hostname: portal
    container_name: portal
    image: bruchbude.nsupdate.info:9002/init-lab/lab_portal:latest
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
     - centos1
     - centos2
     - centos3
     - ubuntu1
     - ubuntu2
     - ubuntu3
    ports:
     - "1000:80"
    networks:
     - diveinto.io

networks:
  diveinto.io:
    name: diveinto.io
    # Canonical bridge interface name
    #
    # The setting below provides a friendly name for the bridge interface
    # as seen in the likes of the ip command.  Use at your own discretion
    #
    #driver_opts:
    #  com.docker.network.bridge.name: "diveinto.io"
